game:
  minplayercount: 2
  maxplayercount: 8
  countaskilldelay: 20

map: #NOTE: use block coordinates (ints without ,s)
  world: world
  centerblock: 2 1 2
  #TODO: add custom areas w custom timers
  centerareafirstcorner: 0 1 0
  centerareasecondcorner: 4 1 4
  spawns:
    - 0 1 0
    - 5 1 5
    - 10 1 10

expiringblock:
  tickbreaktime: 1200
  tickbreakstarttime: 900
  centertickbreaktime: 60
  centertickbreakstarttime: 0
  mincolorchangecount: 1
  maxcolorchangecount: 6

general:
  language: fr
