game:
  minPlayerCount: 2
  maxPlayerCount: 8
map: #NOTE: use block coordinates (ints without ,s)
  centerFirstCorner: [0, 0, 0]
  centerSecondCorner: [5, 5, 5]

  spawns:
    - 0 0 0
    - 0 0 0
    - 0 0 0
   