game:
  minplayercount: 2
  maxplayercount: 8
  countaskilldelay: 20

map: #use block coordinates (ints without ,s)
  world: world
  centerblock: 2 1 2
  areas: #can add custom areas (priority from top to bottom, higher on top)
    closemid:
      corner1: 0 0 0
      corner2: 4 4 4
      tickbreaktime: 60
      tickbreakstarttime: 0
    largemid:
      corner1: -2 0 -2
      corner2: 6 5 6
      tickbreaktime: 200
      tickbreakstarttime: 40

  spawns:
    - 0 1 0, 90 6
    - 5 1 5, 90 6
    - 10 1 10, 90 6

expiringblock:
  defaulttickbreaktime: 1200
  defaulttickbreakstarttime: 900
  mincolorchangecount: 1
  maxcolorchangecount: 6

general:
  language: fr
