game:
  minPlayerCount: 2
  maxPlayerCount: 8
map: #NOTE: use block coordinates (ints without ,s)
  world: world
  centerBlock: 2 1 2
  centerAreaFirstCorner: 0 1 0
  centerAreaSecondCorner: 4 1 4
  spawns:
    - 0 1 0
    - 5 1 5
    - 10 1 10
expiringBlock:
  tickBreakTime: 1200
  tickBreakStartTime: 900
  centerTickBreakTime: 60
  centerTickBreakStartTime: 0
  minColorChangeCount: 1
  maxColorChangeCount: 6
language: fr
