name: BlockSumo
version: 0.2
author: Nixuge
main: me.nixuge.BlockSumo
commands:
  join_blocksumo:
    description: join the blocksumo queue
    usage: /join_blocksumo
  quit_blocksumo:
    description: quit the blocksumo queue
    usage: /quit_blocksumo
  start_blocksumo:
    description: force start the blocksumo queue /!\DEV ONLY/!\
    usage: /start_blocksumo
  testcommand:
    description: test command used for various purposes while testing
    usage: /testcommand